### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by landsman** [studioartcz/wp#1]
- [ ] Use Bedrock skeleton
- [ ] Add composer hooks script
- [ ] Bcrypt
- [ ] Find some template system solution
- [ ] Create template skeleton with: bower, gulp, bootstrap (3/4), sass
- [ ] Think about cool deployment (Gitlab CI, Jenkins job export, ...)
- [ ] Think about https://github.com/versionpress
- [ ] Add requrements to must-have plugins for marketing
